AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.1

inherit_gem:
  rubocop-ronin: rubocop.yml

Naming/PredicateName:
  Exclude:
    - 'lib/ronin/web/session_cookie/cookie.rb'

Security/MarshalLoad:
  Exclude:
    - 'lib/ronin/web/session_cookie/rack.rb'

Style/NumericLiterals:
  Exclude:
    - 'spec/jwt_spec.rb'
    - 'spec/django_spec.rb'
